config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'#トップページ
  devise_for :users,module: :users
  devise_scope :user do
    #プロフィール編集画面へ
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    #プロフィール更新画面へ
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  get 'pages/id',to: 'pages#show'
  resources :pages  do
    get "searchcondition",on: :collection
    get "search" ,on: :collection
    get "about" ,on: :collection
    get "privacy_policy" ,on: :collection
    get "inquiry",on: :collection
  end

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :mypage,only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.erb
<div class='site-share'>
<p>このサイトをシェアする</p>
<a href="https://twitter.com/share?url=https://www.bandrec.net&バンドメンバー募集" target="_blank" class="btn btn-info btn-lg" data-show-count="false">Twitter</a>
<a href="https://www.facebook.com/sharer/sharer.php?u=https://www.bandrec.net" target="_blank" class="btn btn-info btn-lg" data-show-count="false">Facebook</a>
<a href="https://line.me/R/msg/text/?https://www.bandrec.net" target="_blank" class="btn btn-info btn-lg" data-show-count="false">LINE</a>
</div>
<div class="copyright">Copyright ©︎bandrec </div><br>
  <div class="horizonal-list">
      <%= link_to 'bandrecとは', "/pages/about",:class => "bandrectoha" %> |
      <%= link_to 'お問い合わせ', "/pages/inquiry" %> |
      <%= link_to '利用規約', "/pages/privacy_policy" %> |
      <% if user_signed_in? %>
      <%= link_to "アカウント削除","/users/#{current_user}", method: :delete, data: { confirm: '本当にアカウントを削除しますか？' } %>
      <% end %>
  </div>

app/views/shared/_header.html.erb
<div class="header-list container">
<div class="h-menu row">

<div class='col-md-3'></div>
<div class='col-md-6'>
<%= link_to '', "/",class:"fa fa-home menu-icon" %>
<%= link_to '', "/pages/searchcondition",class: "fa fa-search menu-icon" %>
<% if current_user %>
        <%= link_to '', "/rooms",class:"fa fa-envelope menu-icon" %>
    <% else %>
        <%= link_to '', "/users/sign_up",class:"fa fa-envelope menu-icon" %>
<% end %>


    <% if current_user %>
        <%= link_to '', mypage_path(current_user),class:"fa fa-user menu-icon" %>
    <% else %>
        <%= link_to '', "/users/sign_up",class:"fa fa-user menu-icon" %>
    <% end %>
    </div>
    </div>
<div class='col-md-3'></div>
</div>

app/views/shared/_sidemenu.html.erb
<h2 class="hidden">サイドメニュー</h2>
<% if current_user %>
  <div class="profile">
  <% if current_user.profile_picture.attached? %>
    <%= image_tag  current_user.profile_picture,:class => "image" %>
  <% else %>
        <%= image_tag  "account.png",class:"image" %>
  <% end %>
  <p class="name"><%= current_user.name %><span class="user-type">
    <% if current_user.user_type == 1 %>
      加入希望
    <% elsif current_user.user_type == 2 %>
      メンバー募集
      <% else %>
      休憩モード
    <% end %></span></p>
    <%= link_to 'マイページ', mypage_path(current_user),:class => "edit" %>
</div>
<% end %>

<h2 class="hidden">message</h2>
  <div class="message">
  <%#<a class="text">メッセージ<span class="message-count">1</span></a>%>
<% if current_user %>
<% noreply_array = [] %>
<% noreply(current_user,noreply_array) %>
<%= link_to "未返信メッセージ #{noreply_array.count} 件", "/rooms",:class => "noreply-message" %>
<% else %>
<a class="text">メッセージ</a>
<% end %>
</div>
<h2 class="hidden">SidemenuFunction</h2>
<div class="side-function">
  <ul>
    <li><%= link_to 'ユーザーを検索する', "/pages/searchcondition" %></li>
    <li> <%= link_to 'お問い合わせ', "/pages/inquiry" %> </li>
  </ul>
</div>