config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'#トップページ
  devise_for :users,module: :users
  devise_scope :user do
    #プロフィール編集画面へ
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    #プロフィール更新画面へ
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  get 'pages/id',to: 'pages#show'
  resources :pages  do
    get "searchcondition",on: :collection
    get "search" ,on: :collection
    get "about" ,on: :collection
    get "privacy_policy" ,on: :collection
    get "inquiry",on: :collection
  end

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :mypage,only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :messages, dependent: :destroy
  has_many :entries, dependent: :destroy
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :authenticate_user!
  #before_action :prereg #事前登録が終わったら消す


  def prereg
    redirect_to :new_user_registration
  end

  def index #メッセージ一覧を表示する
    @currentEntries = current_user.entries #ログイン中のユーザーが入ることのできる部屋(room)の鍵情報たち
    myRoomIds = []
    @currentEntries.each do |entry|
    myRoomIds << entry.room.id #自分が入ることができる部屋(room)のid
  end

  @anotherEntries = Entry.where(room_id: myRoomIds).where('user_id != ?',current_user.id) #自分が入ることができる部屋(Room)かつuser_idが自分のidではない
  end

  def create #部屋(チャットルーム)を作る
    @room = Room.create
    @entry1 = Entry.create(:room_id => @room.id, :user_id => current_user.id)
    @entry2 = Entry.create(params.require(:entry).permit(:user_id, :room_id).merge(:room_id => @room.id))
    redirect_to "/rooms/#{@room.id}" #部屋へ
  end

  def show #すでにある部屋(チャットルーム)を表示する
    @room = Room.find(params[:id])
    if Entry.where(:user_id => current_user.id, :room_id => @room.id).present?
      @messages = @room.messages
      @message = Message.new
      @entries = @room.entries
    else
      redirect_back(fallback_location: root_path)
    end
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="room-index">
<h2>メッセージ一覧</h2>
<%count = 0%>
<% @anotherEntries.reverse.each do |e| %>

<div class= "room-content">
<% if e.room.messages[count]== nil %>
<%count += 1%>
<% else %>

  <%= link_to room_path(e.room.id) do %>
        <% if e.user.profile_picture.attached? %>
        <%= image_tag e.user.profile_picture,:class => "image" %>
        <% else %>
              <%= image_tag  "account.png",class:"image" %>
        <% end %>
    <%= e.user.name %>
              <% e.room.messages.each_with_index do |em,index|  %>
                <% if index == e.room.messages.size - 1 %>
                  <% if em.user_id != current_user.id  %>
                  <span class="noreply">未返信</span>
                  <% end %>
              <% end %>
            <% end %>
  <% end %>
<% end %>
</div>



<%count += 1%>
<% end %>
</div>

app/views/rooms/show.html.erb
<div class="chat-box container">
<h1 class="hidden">メッセージ</h1>
<div class='row'>
<div class='col-md-0'></div>
<div class='col-md-12'>
<% @entries.each do |e| %>
<% if e.user_id == current_user.id %>
<% else %>
  <h5><strong><a href="/pages/<%= e.user.public_uid %>"><%= e.user.name%>さん</a></strong></h5>
  <% end %>
<% end %>

<div class="line-bc"><!--①LINE会話全体を囲う-->
<% if @messages.present? %>
<% @messages.each do |m| %>
<% if m.user_id == current_user.id %>
<!--③右コメント始-->
  <div class="mycomment">
  <span class="speech-time"><%= m.created_at.strftime("%m-%d %H:%M") %></span>
    <p>
    <%= m.content %>
    </p>
  </div>
  <!--/③右コメント終-->

<% else %>
<!--②左コメント始-->
  <div class="balloon6">
    <div class="faceicon">
    <% if m.user.profile_picture.attached? %>
    <%= image_tag  m.user.profile_picture,class:"chat-image" %>
  <% else %>
        <%= image_tag  "account.png",class:"image" %>
  <% end %>
    </div>
    <div class="chatting">
      <div class="says">
        <p><%= m.content %></p>
      </div>
      <span class="speech-time"><%= m.created_at.strftime("%m-%d %H:%M") %></span>
    </div>
  </div>
  <!--②/左コメント終-->
  <% end %>
<% end %>
 <% else %>
    <h3 class="text-center"></h3>
  <% end %>
</div>

  <%= form_for @message do |f| %>
    <%= f.text_area :content, :placeholder => "メッセージを入力して下さい" , :size => "98x3",class:"chat-text-area form-control" %>
    <%= f.hidden_field :room_id, :value => @room.id %>
    <br>
    <%= f.submit "送信",:class=>"btn btn-primary btn-lg" %>
  <% end %>
  </div>
  <div class='col-md-0'></div>
  </div>
</div>