config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'#トップページ
  devise_for :users,module: :users
  devise_scope :user do
    #プロフィール編集画面へ
    get 'profile_edit', to: 'users/registrations#profile_edit', as: 'profile_edit'
    #プロフィール更新画面へ
    patch 'profile_update', to: 'users/registrations#profile_update', as: 'profile_update'
  end
  get 'pages/id',to: 'pages#show'
  resources :pages  do
    get "searchcondition",on: :collection
    get "search" ,on: :collection
    get "about" ,on: :collection
    get "privacy_policy" ,on: :collection
    get "inquiry",on: :collection
  end

  resources :messages, :only => [:create]
  resources :rooms, :only => [:create, :show, :index]
  resources :mypage,only:[:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/mypage_controller.rb
class MypageController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/mypage_helper.rb
module MypageHelper
end

app/views/mypage/show.html.erb
<h2 class="hidden">マイページ</h2>
<div class="mypage-box">
<h3 class="hidden">登録データ</h3>
  <div class="top-box clearfix">
    <div class="image-box">
      <% if @user.profile_picture.attached? %>
      <%= image_tag  @user.profile_picture,class:"user_image" %>
      <% else %>
      <%= image_tag  "account.png",class:"user_image" %>
      <% end %>
    </div>
      <div class="data-box">
      名前：<%= @user.name %><br>
      <% if @user.user_type == 1 %>
        加入希望<br>
        担当パート：<% @user.instruments.each do |i| %>
          <% case i.part %>
            <% when 1 %>
            Vo
            <% when 2 %>
            Gt
            <% when 3 %>
            Ba
            <% when 4 %>
            Key
            <% when 5 %>
            Dr
            <% end %>
          <% end %><br>
          年齢：
          <% if @user.birthday != nil %>
          <% date_format = "%Y%m%d" %>
          <% if (Date.today.strftime(date_format).to_i - @user.birthday.strftime(date_format).to_i) / 10000 == 0 %>
          未設定<br>
          <% else %>
          <%= (Date.today.strftime(date_format).to_i - @user.birthday.strftime(date_format).to_i) / 10000 %> 才<br>
          <% end %>
        <% else %>
        未入力<br>
        <% end %>
        活動エリア：<%= @user.area %><br>
        性別：<% if @user.gender == 1 %>
      男
      <% else %>
      女
      <% end %><br>
      <% elsif @user.user_type == 2 %>
        メンバー募集<br>
        募集パート：<% @user.instruments.each do |i| %>
          <% case i.part %>
            <% when 1 %>
            Vo
            <% when 2 %>
            Gt
            <% when 3 %>
            Ba
            <% when 4 %>
            Key
            <% when 5 %>
            Dr
            <% end %>
          <% end %><br>
          活動エリア：<%= @user.area %><br>
      <% else %>
        休憩モード(検索結果に表示されません)<br>
      <% end %>
      </div>
      <div class="sound_source-box">
      <h3 class="hidden">自分が投稿した音源</h3>
        音源<br><%= text_url_to_link(h(@user.sound_source)).html_safe %>
      </div>
    </div>
  <div class="info-box">
  <h3 class="hidden">自己紹介</h3>
    <%= simple_format(@user.info) %>
  </div>
  <br>
  <div class='prof-edit fas fa-edit'><%= link_to 'プロフィール編集', profile_edit_path %></div><br><br>
  <div class="prof-logout fas fa-sign-out-alt"><%= link_to 'ログアウト', "/users/sign_out", method: :delete %></div>
</div>